services:
  - type: web
    name: quiz-portal-backend
    env: node
    buildCommand: cd Backend && npm install
    startCommand: cd Backend && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://Abinivesh_M:Abinivesh%402007@cluster0.agf1q7w.mongodb.net/quizportal
      - key: JWT_SECRET
        value: quiz_portal_secret_2024
      - key: CORS_ORIGIN
        value: "*"

  - type: web
    name: quiz-portal-frontend
    env: static
    buildCommand: cd Frontend && npm install && REACT_APP_API_URL=https://quiz-portal-backend.onrender.com/api npm run build
    staticPublishPath: Frontend/build